### ISSUE TITLE
Is the 2017 - 2020 contamination report available?

### ISSUE THREAD

**Issue by zjysteven** [liyucheng09/Contamination_Detector#3]
Hi,

Thanks for putting up this work and all these useful results. I'm particularly interested in LLaMA's contamination, and you mentioned that the corresponding search window for them was 2017 - 2020, different from other models' 2017 - 2023.

I was thus wondering if the reports under `reports/` are for 2017 - 2020 or for 2017 - 2023? If it's the latter, are the reports for 2017 - 2020 available at the moment?

Thanks

**Comment by zjysteven** [comment]
Oh I just noticed there is a `llama-report` branch. Is that something I should look into?

**Comment by liyucheng09** [comment]
The reports in the main branch was for LLMs that have unknown cutoff date (for which the search window is 27-23).
The reports for 2017-2020 is specifically for llama model.

I got 2017-2020 reports for MMLU and ARC that are ready to commits. I will do it soon.
For other benchmarks I might need some time to sort it out.

**Comment by zjysteven** [comment]
Thank you! Having those two reports would already be helpful.

**Comment by zjysteven** [comment]
@liyucheng09 Hi Yucheng, would you kindly let me know when do you plan to make the commits? Not trying to push you in any sense, but I'd like to have a rough idea.

**Comment by liyucheng09** [comment]
Sorry for the late reply.
These files are on our department remote server, took me sometime to find them.

Please check the reports of ARC and MMLU during 17-20 at [here](https://github.com/liyucheng09/Contamination_Detector/tree/master/reports/llama).

Note that the current MMLU annotation is not complete.
Not exactly sure why, but I will re-run the pipeline to generate a complete report.
I will keep you updated.

**Comment by zjysteven** [comment]
No worries. Thank you again.

**Comment by liyucheng09** [comment]
@zjysteven Hi Jinayang, please check out the updated MMLU reports under `reports/llama` where I just rerun the 17-20 search for MMLU. It now covers more MMLU instances.

Please consider leave a star if you find this helpful!

**Comment by zjysteven** [comment]
Thank you👍! Just starred (should have done earlier).
